### ISSUE TITLE
render error with unique values

### ISSUE THREAD

**Issue by ogmueller** [noximo/PHP-colored-ascii-linechart#3]
If all values are the same the output is broken.

An example would be
```
$linechart = new Linechart();
echo $linechart->addMarkers([1,1,1])->chart();
```
I know this is an edge case, but I am using the graph to show temperature over time. If the temperature is not changing, the graph is broken and looks like this:
```
     1┤
  ───
```

it should render like this:
```
     1┤───
```

Somehow the line number calculated in \noximo\PHPColoredAsciiLinechart\Linechart::processLinearGraph (Line 417) is off by one. The result has two rows, even though there is only one line in the graph.

Setting the height is also not helping, it will reproduce the same:
```
$linechart = new Linechart();
$settings = new Settings();
$settings->setHeight(5);
echo $linechart->setSettings($settings)->addMarkers([1,1,1])->chart();
```

**Comment by noximo** [comment]
Thanks for the report, should be fixed now.

**Comment by ogmueller** [comment]
It works now. Great.

But with zeros, it will throw an error:

```
$linechart = new Linechart();
echo $linechart->addMarkers([0,0,0])->chart();
```

results in

```
In Linechart.php line 396:
  Warning: Division by zero
```
